version: '3.8'
services:
  pdi:
    image: pdi
    container_name: pdi
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}:/workdir
      - ~/pentaho/:/pdi